# 🏦 Bank Loan Data Analysis Dashboard
**Author:** Shawon | **Role:** Data Analyst 📊  
**Goal:** To analyze total funded amounts, loan purposes, and home ownership patterns.
---

### Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings 
warnings.filterwarnings('ignore')

### Import Dataset

In [2]:
data = pd.read_excel("row data.xlsx")

In [3]:
data.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

In [109]:
# check data type
data.dtypes

id                                int64
address_state                    object
application_type                 object
emp_length                       object
emp_title                        object
grade                            object
home_ownership                   object
issue_date               datetime64[ns]
last_credit_pull_date    datetime64[ns]
last_payment_date        datetime64[ns]
loan_status                      object
next_payment_date        datetime64[ns]
member_id                         int64
purpose                          object
sub_grade                        object
term                             object
verification_status              object
annual_income                   float64
dti                             float64
installment                     float64
int_rate                        float64
loan_amount                       int64
total_acc                         int64
total_payment                     int64
month_name                       object
month_num                         int32
dtype: object

In [110]:
print(f"No of column : {data.shape[1]} ")
print(f"No of Row : {data.shape[0]}")

No of column : 26
No of Row : 38576

In [ ]:
#Basic summary of statistics

data.describe()

,id,issue_date,last_credit_pull_date,last_payment_date,next_payment_date,member_id,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
count,3.857600e+04,38576,38576,38576,38576,3.857600e+04,3.857600e+04,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000,38576.000000
mean,6.810371e+05,2021-07-16 02:31:35.562007040,2021-06-08 13:36:34.193280512,2021-06-26 09:52:08.909166080,2021-07-26 20:42:20.605557760,8.476515e+05,6.964454e+04,0.133274,326.862965,0.120488,11296.066855,22.132544,12263.348533
min,5.473400e+04,2021-01-01 00:00:00,2021-01-08 00:00:00,2021-01-08 00:00:00,2021-02-08 00:00:00,7.069900e+04,4.000000e+03,0.000000,15.690000,0.054200,500.000000,2.000000,34.000000
25%,5.135170e+05,2021-04-11 00:00:00,2021-04-15 00:00:00,2021-03-16 00:00:00,2021-04-16 00:00:00,6.629788e+05,4.150000e+04,0.082100,168.450000,0.093200,5500.000000,14.000000,5633.000000
50%,6.627280e+05,2021-07-11 00:00:00,2021-05-16 00:00:00,2021-06-14 00:00:00,2021-07-14 00:00:00,8.473565e+05,6.000000e+04,0.134200,283.045000,0.118600,10000.000000,20.000000,10042.000000
75%,8.365060e+05,2021-10-11 00:00:00,2021-08-13 00:00:00,2021-09-15 00:00:00,2021-10-15 00:00:00,1.045652e+06,8.320050e+04,0.185900,434.442500,0.145900,15000.000000,29.000000,16658.000000
max,1.077501e+06,2021-12-12 00:00:00,2022-01-20 00:00:00,2021-12-15 00:00:00,2022-01-15 00:00:00,1.314167e+06,6.000000e+06,0.299900,1305.190000,0.245900,35000.000000,90.000000,58564.000000
std,2.113246e+05,NaN,NaN,NaN,NaN,2.668105e+05,6.429368e+04,0.066662,209.092000,0.037164,7460.746022,11.392282,9051.104777

## Total Loan Application

In [8]:
total_loan_application = data['id'].count()
print("Total Loan Application : ",total_loan_application)

Total Loan Application :  38576

In [9]:
Latest_issue_date = data['issue_date'].max()
Latest_issue_year = Latest_issue_date.year
Latest_issue_month = Latest_issue_date.month



MTD_data = data[(data['issue_date'].dt.year == Latest_issue_year ) & (data['issue_date'].dt.month == Latest_issue_month)]
MTD_total_loan_application = MTD_data['id'].count()

print(f"MTD Total Loan Application : {MTD_total_loan_application} ")

MTD Total Loan Application : 4314

In [10]:
total_funded_amount = data['loan_amount'].sum()
total_funded_amount_in_million  = (total_funded_amount / 1000000).round(2)
print(f"Total Funded Amount : ${total_funded_amount_in_million}M")

Total Funded Amount : $435.76M

In [11]:
Latest_issue_date = data['issue_date'].max()
Latest_issue_year = Latest_issue_date.year
Latest_issue_month = Latest_issue_date.month
MTD_data = data[(data['issue_date'].dt.year == Latest_issue_year ) & (data['issue_date'].dt.month == Latest_issue_month)]


MTD_Total_Funded_amount_in_million = (MTD_data['loan_amount'].sum() / 1000000).round(2)
print(f"MTD TOTAL FUNDED AMOUNT :  ${MTD_Total_Funded_amount_in_million}M")

MTD TOTAL FUNDED AMOUNT :  $53.98M

In [12]:
Total_received_Amount = (data['total_payment'].sum() / 1000000 ).round(2)
print(f"TOTAL RECEIVED AMOUNT : ${Total_received_Amount}M")

TOTAL RECEIVED AMOUNT : $473.07M

In [13]:
Latest_issue_date = data['issue_date'].max()
Latest_issue_year = Latest_issue_date.year
Latest_issue_month = Latest_issue_date.month
MTD_data = data[(data['issue_date'].dt.year == Latest_issue_year ) & (data['issue_date'].dt.month == Latest_issue_month)]


MTD_TOTAL_Received_amount = (MTD_data['total_payment'].sum() / 1000000).round(2)
print(f"MTD TOTAL RECEIVED AMOUNT : ${MTD_TOTAL_Received_amount}M")

MTD TOTAL RECEIVED AMOUNT : $58.07M

In [14]:
data.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

In [15]:
average_interest_rate = (data['int_rate'].mean() * 100).round(2)
print(f"Average interest rate : {average_interest_rate} % ")

Average interest rate : 12.05 %

In [16]:
average_dti_rate = (data['dti'].mean() *100).round(2)
print(f"Average Dti Rate : {average_dti_rate} %")

Average Dti Rate : 13.33 %

### GOOD LOAN METRICS

In [17]:
data.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,sub_grade,term,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,C4,60 months,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,E1,36 months,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,C5,36 months,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,B2,60 months,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,A1,36 months,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835

In [18]:
data['loan_status'].unique()

array(['Charged Off', 'Fully Paid', 'Current'], dtype=object)

In [19]:
# Total good loans
good_loans = data[data['loan_status'].isin(['Fully Paid','Current'])]

Good_Loans_Total_Application = good_loans['id'].count()
Good_Loans_Total_Funded_Amount = good_loans['loan_amount'].sum()
Good_Loans_Total_Received_Amount = good_loans['total_payment'].sum()

Good_Loans_Total_Funded_Amount_million = (Good_Loans_Total_Funded_Amount / 1000000).round(2)
Good_Loans_Total_Received_million = (Good_Loans_Total_Received_Amount/ 1000000).round(2)
Good_Loans_Percentage = ((Good_Loans_Total_Application / total_loan_application)*100).round(2)


print(f"GOOD LOAN TOTAL APPLICATION         : {Good_Loans_Total_Application}")
print(f"GOOD LOAN TOTAL FUNDED AMOUNT       : ${Good_Loans_Total_Funded_Amount_million}M")
print(f"GOOD LOAN TOTAL RECEIVED AMOUNT     : ${Good_Loans_Total_Received_million}M")
print(f"PERCENTAGE OF GOOD LOAN APPLICATION : {Good_Loans_Percentage}%")

GOOD LOAN TOTAL APPLICATION         : 33243
GOOD LOAN TOTAL FUNDED AMOUNT       : $370.22M
GOOD LOAN TOTAL RECEIVED AMOUNT     : $435.79M
PERCENTAGE OF GOOD LOAN APPLICATION : 86.18%

### BAD LOAN METRICS

In [20]:
# Total Bad  loans
BAD_loans = data[data['loan_status'].isin(['Charged Off'])]

BAD_Loans_Total_Application = BAD_loans['id'].count()
BAD_Loans_Total_Funded_Amount = BAD_loans['loan_amount'].sum()
BAD_Loans_Total_Received_Amount = BAD_loans['total_payment'].sum()

BAD_Loans_Total_Funded_Amount_million = (BAD_Loans_Total_Funded_Amount / 1000000).round(2)
BAD_Loans_Total_Received_million = (BAD_Loans_Total_Received_Amount/ 1000000).round(2)
BAD_Loans_Percentage = ((BAD_Loans_Total_Application / total_loan_application)*100).round(2)


print(f"BAD LOAN TOTAL APPLICATION         : {BAD_Loans_Total_Application}")
print(f"BAD LOAN TOTAL FUNDED AMOUNT       : ${BAD_Loans_Total_Funded_Amount_million}M")
print(f"BAD LOAN TOTAL RECEIVED AMOUNT     : ${BAD_Loans_Total_Received_million}M")
print(f"PERCENTAGE OF BAD LOAN APPLICATION : {BAD_Loans_Percentage}%")

BAD LOAN TOTAL APPLICATION         : 5333
BAD LOAN TOTAL FUNDED AMOUNT       : $65.53M
BAD LOAN TOTAL RECEIVED AMOUNT     : $37.28M
PERCENTAGE OF BAD LOAN APPLICATION : 13.82%

### 📉 Monthly Loan Trends (Total Funded Amount)

In [113]:
#create month_name and month_num column 

data['month_name'] = data['issue_date'].dt.strftime('%b')
data['month_num'] = data['issue_date'].dt.month

# Loan amount Group by Month_num
Monthly_funded  = data.groupby(["month_num","month_name"])['loan_amount'].sum().reset_index().sort_values('month_name')
Monthly_funded = Monthly_funded.sort_values('month_num').drop('month_num', axis = 1)
Monthly_funded['loan_amount'] = (Monthly_funded['loan_amount'] / 1000000).round(1)

fig = px.line(data_frame= Monthly_funded, x='month_name', y = 'loan_amount',
              text='loan_amount',title='Total Funded Amount by Month',height=450, width=900, template='simple_white')
fig.update_xaxes(showgrid = False)
fig.update_yaxes(showgrid = False)
fig.update_layout(
    title_x = 0.48,
    paper_bgcolor = 'white',
    plot_bgcolor = 'white',
    font = dict(family = 'arial', color = 'black',weight = 'bold')
    
)
fig.update_traces(
    textposition = 'top center',
    line=dict(width=4, color='royalblue'), 
    marker=dict(size=10, symbol='circle'), 
    mode='lines+markers+text',
    textfont = dict(family = 'Arial', weight  ='bold')
)
fig.write_image("Total Funded Amount by Month.png", width=900, height=450, scale=5)
fig.show()

## 📉 Monthly Loan Trends (Total Received Amount)

In [ ]:

Monthly_recived  = data.groupby(["month_num","month_name"])['total_payment'].sum().reset_index().sort_values('month_name')
Monthly_recived = Monthly_recived.sort_values('month_num').drop('month_num', axis = 1)
Monthly_recived['total_payment'] = (Monthly_recived['total_payment'] / 1000000).round(1)

fig = px.line(data_frame= Monthly_recived, x='month_name', y = 'total_payment',
              text='total_payment',title='Total Received Amount by Month',height=450, width=900, template='simple_white')
fig.update_xaxes(showgrid = False)
fig.update_yaxes(showgrid = False)
fig.update_layout(
    title_x = 0.48,
    paper_bgcolor = 'white',
    plot_bgcolor = 'white',
    font = dict(family = 'arial', color = 'black',weight = 'bold')
    
)
fig.update_traces(
    textposition = 'top center',
    line=dict(width=4, color='green'), 
    marker=dict(size=10, symbol='circle'), 
    mode='lines+markers+text',
    textfont = dict(family = 'Arial', weight  ='bold')
)
fig.show()

## 📉 Monthly Loan Trends (Total Loan Application)

In [ ]:

Monthly_total_application  = data.groupby(["month_num","month_name"])['id'].count().reset_index().sort_values('month_name')
Monthly_total_application = Monthly_total_application.sort_values('month_num').drop('month_num', axis = 1)
Monthly_total_application = Monthly_total_application.rename(columns={'id':'Total_Application'})



fig = px.line(data_frame= Monthly_total_application, x='month_name', y = 'Total_Application',
              text='Total_Application',title='Total Loan Application by Month',height=450, width=900, template='simple_white')
fig.update_xaxes(showgrid = False)
fig.update_yaxes(showgrid = False)
fig.update_layout(
    title_x = 0.48,
    paper_bgcolor = 'white',
    plot_bgcolor = 'white',
    font = dict(family = 'arial', color = 'black',weight = 'bold')
    
)
fig.update_traces(
    textposition = 'top center',
    line=dict(width=4, color = "skyblue"), 
    marker=dict(size=10, symbol='circle'), 
    mode='lines+markers+text',
    textfont = dict(family = 'Arial', weight  ='bold')
)
fig.show()

### 📍 Geographical Distribution

In [76]:
top_10_state_wise_total_funded = data.groupby('address_state')['loan_amount'].sum().reset_index().sort_values(by='loan_amount',ascending=False).head(10)


fig = px.bar(data_frame= top_10_state_wise_total_funded, y='address_state', x='loan_amount',text_auto='.2s',color='address_state',
             title='Total Funded Amount by State',color_discrete_sequence=px.colors.sequential.Greys_r)
fig.update_xaxes(showgrid = False)
fig.update_yaxes(showgrid = False)
fig.update_layout(
    title_x = 0.48,
    paper_bgcolor = 'white',
    plot_bgcolor = 'white',
    font = dict(family = 'arial', color = 'black'),
    showlegend = False
    
)
fig.update_traces(
    textposition = 'outside'
)

fig.show()

In [27]:
data.head()

,id,address_state,application_type,emp_length,emp_title,grade,home_ownership,issue_date,last_credit_pull_date,last_payment_date,...,verification_status,annual_income,dti,installment,int_rate,loan_amount,total_acc,total_payment,month_name,month_num
0,1077430,GA,INDIVIDUAL,< 1 year,Ryder,C,RENT,2021-02-11,2021-09-13,2021-04-13,...,Source Verified,30000.0,0.0100,59.83,0.1527,2500,4,1009,Feb,2
1,1072053,CA,INDIVIDUAL,9 years,MKC Accounting,E,RENT,2021-01-01,2021-12-14,2021-01-15,...,Source Verified,48000.0,0.0535,109.43,0.1864,3000,4,3939,Jan,1
2,1069243,CA,INDIVIDUAL,4 years,Chemat Technology Inc,C,RENT,2021-01-05,2021-12-12,2021-01-09,...,Not Verified,50000.0,0.2088,421.65,0.1596,12000,11,3522,Jan,1
3,1041756,TX,INDIVIDUAL,< 1 year,barnes distribution,B,MORTGAGE,2021-02-25,2021-12-12,2021-03-12,...,Source Verified,42000.0,0.0540,97.06,0.1065,4500,9,4911,Feb,2
4,1068350,IL,INDIVIDUAL,10+ years,J&J Steel Inc,A,MORTGAGE,2021-01-01,2021-12-14,2021-01-15,...,Verified,83000.0,0.0231,106.53,0.0603,3500,28,3835,Jan,1

### ⏳ Loan Term Comparison

In [ ]:
Term_funding_amount = data.groupby('term')['loan_amount'].sum().reset_index()
Term_funding_amount


fig = px.pie(data_frame=Term_funding_amount, names='term' , values='loan_amount', width=500, hole=0.6, template='plotly_dark',title='Total Funded Amount by Term')
fig.update_xaxes(showgrid = False)
fig.update_yaxes(showgrid = False)
fig.update_layout(
    title_x = 0.48,
    paper_bgcolor='black',
    plot_bgcolor = 'black',
    font = dict(family = 'arial', color = 'white'),
    # showlegend = False
    
)
fig.update_traces(textinfo='label+value',
                  textposition = 'outside',
                  texttemplate='%{label}<br>%{value:.4s}')

fig.show()

### 📊 Total Funded Amount by Employment Length

In [ ]:
total_funded_amount_emp_length = data.groupby('emp_length')['loan_amount'].sum().reset_index().sort_values(by='loan_amount', ascending=False)


fig = px.bar(data_frame= total_funded_amount_emp_length, x='emp_length', y='loan_amount',text_auto='.3s',color='emp_length',
             title='Total Funded Amount by Employement Length',color_discrete_sequence=px.colors.sequential.Blues_r,height=500)
fig.update_xaxes(showgrid = False)
fig.update_yaxes(showgrid = False,showticklabels=False,title_text=None)
fig.update_layout(
    title_x = 0.48,
    paper_bgcolor = 'white',
    plot_bgcolor = 'white',
    font = dict(family = 'arial', color = 'black'),
    showlegend = False
     
    
)
fig.update_traces(
    textposition = 'outside'
)
fig.show()

### 🎯 Loan Purpose Analysis

In [108]:
loan_purpose_by_total_funded_amount = data.groupby('purpose')['loan_amount'].sum().reset_index().sort_values(by='loan_amount', ascending=False)



fig = px.bar(data_frame= loan_purpose_by_total_funded_amount, y='purpose', x='loan_amount',text_auto='.3s',color='purpose',
             title='Total Funded Amount by Loan Purpose',color_discrete_sequence=px.colors.sequential.Blues_r)
fig.update_xaxes(showgrid = False)
fig.update_yaxes(showgrid = False)
fig.update_layout(
    title_x = 0.48,
    paper_bgcolor = 'white',
    plot_bgcolor = 'white',
    font = dict(family = 'arial', color = 'black'),
    showlegend = False
     
    
)
fig.update_traces(
    textposition = 'outside'
)

fig.show()

### 🏠 Home Ownership Distribution

In [ ]:
home_ownership_by_total_funded_amount = data.groupby('home_ownership')['loan_amount'].sum().reset_index().sort_values(by='loan_amount', ascending=False)

fig = px.treemap(
    data_frame=home_ownership_by_total_funded_amount,
    path=['home_ownership'],
    values='loan_amount',
    color='loan_amount', 
    color_continuous_scale='Blues',
    title='Total Funded Amount by Home Ownership'
     
)

fig.update_layout(
    template='plotly_dark',
    paper_bgcolor='#1e1e1e',
    plot_bgcolor='#1e1e1e',
    coloraxis_showscale=False ,
    title_x = 0.5
)

fig.update_traces(
    textinfo="label+value",
    texttemplate='%{label}<br>%{value:.1s}'
)
fig.show()

# 🏦 Bank Loan Analysis - Executive Summary

After a comprehensive analysis of the loan dataset, several key patterns regarding borrower behavior and credit distribution have been identified:

### 1. 🎯 Primary Loan Drivers
* **Debt Consolidation:** The vast majority of loan applications are driven by 'Debt Consolidation.' This indicates that a significant portion of the customer base is seeking to manage or refinance existing liabilities. 💰
* **Secondary Needs:** Credit card payments and home improvements emerge as the next most frequent reasons for borrowing, highlighting a focus on personal financial restructuring. 💳

### 2. 🏠 Housing & Risk Correlation
* **Renters and Mortgage Holders:** Borrowers who live in rented accommodations or have existing mortgages account for the highest total funded amounts. 🏠
* **Homeowners:** Those who fully own their homes represent the smallest segment of borrowers, which may suggest higher financial stability and lower credit dependency within this group. 💸

### 3. 💼 Impact of Employment Stability
* **Job Tenure:** There is a direct correlation between employment length and the total funded amount. Borrowers with **10+ years** of experience receive the highest volume of funding, suggesting that the bank favors long-term employment as a key indicator of repayment capacity. 📈

### 4. 📍 Geographical Distribution
* **Key Regions:** Loan activity is heavily concentrated in specific states (e.g., CA, NY, TX). These regions represent the highest market share, and targeted marketing strategies in these areas could further optimize loan growth. 🗺️

### 5. 📉 Seasonal Trends
* **Quarterly Growth:** The analysis shows a gradual increase in loan funding toward the end of the calendar year. This seasonal trend is likely linked to holiday spending and year-end financial planning by customers. ⏳